/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFooter: typeof import('./src/components/adminLayout/AdminFooter.vue')['default']
    AdminHeader: typeof import('./src/components/adminLayout/AdminHeader.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    ChartBar: typeof import('./src/components/adminLayout/dashboard/ChartBar.vue')['default']
    ChartPie: typeof import('./src/components/adminLayout/dashboard/ChartPie.vue')['default']
    CourseCard: typeof import('./src/components/publicLayout/home/CourseCard.vue')['default']
    CourseForm: typeof import('./src/components/adminLayout/courses/CourseForm.vue')['default']
    CourseHeroComponent: typeof import('./src/components/publicLayout/detail/CourseHeroComponent.vue')['default']
    CoursesFilter: typeof import('./src/components/publicLayout/home/CoursesFilter.vue')['default']
    EmptyState: typeof import('./src/components/publicLayout/myCourses/EmptyState.vue')['default']
    EnrollComponent: typeof import('./src/components/publicLayout/detail/EnrollComponent.vue')['default']
    FooterComponent: typeof import('./src/components/publicLayout/FooterComponent.vue')['default']
    KpiCard: typeof import('./src/components/adminLayout/dashboard/KpiCard.vue')['default']
    ListCoursesComponent: typeof import('./src/components/publicLayout/home/ListCoursesComponent.vue')['default']
    ListUsersComponent: typeof import('./src/components/adminLayout/users/ListUsersComponent.vue')['default']
    LoginFormComponent: typeof import('./src/components/publicLayout/LoginFormComponent.vue')['default']
    MyCourseCard: typeof import('./src/components/publicLayout/myCourses/MyCourseCard.vue')['default']
    MyCourseList: typeof import('./src/components/publicLayout/myCourses/MyCourseList.vue')['default']
    MyCoursesList: typeof import('./src/components/publicLayout/myCourses/MyCoursesList.vue')['default']
    NavComponent: typeof import('./src/components/publicLayout/NavComponent.vue')['default']
    RegisterFormComponent: typeof import('./src/components/publicLayout/RegisterFormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateCourseModal: typeof import('./src/components/adminLayout/courses/UpdateCourseModal.vue')['default']
    UpdateUserModal: typeof import('./src/components/adminLayout/users/UpdateUserModal.vue')['default']
    UserCardComponent: typeof import('./src/components/adminLayout/users/UserCardComponent.vue')['default']
    UserFiltersComponent: typeof import('./src/components/adminLayout/users/UserFiltersComponent.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
